### ISSUE TITLE
bots should create PRs here for deploying updated images

### ISSUE THREAD

**Issue by jsnshrmn** [edgi-govdata-archiving/web-monitoring-ops#1]
When we build new images for [db](https://github.com/edgi-govdata-archiving/web-monitoring-db), [processing](https://github.com/edgi-govdata-archiving/web-monitoring-processing), and [ui](https://github.com/edgi-govdata-archiving/web-monitoring-ui), references to those images should make their way here so that a human doesn't have to copy the identifiers into the deployment configuration located here..

**Comment by Mr0grog** [comment]
I think the way to approach this is *probably* piecemeal — repos that publish images should have a CircleCI task that clones this repo, commits a change, and either creates a PR or commits to master (not sure which).
