### ISSUE TITLE
Create Runbook/Process Guide for Things We Do Manually

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ops#15]
There are some manual processes we regularly do that aren’t just deploying software. For example: https://github.com/edgi-govdata-archiving/web-monitoring/issues/130

It would be good to have somewhere clear to document these things; probably in this repo, but maybe it needs to be somewhere more private where we can share more sensitive info, like IP addresses, port numbers, keys, etc.

**Comment by Mr0grog** [comment]
@ibuys any thoughts on this?

**Comment by ibuys** [comment]
My first thought is that Github allows unlimited free private repos now, we could set one up for runbooks.

**Comment by Mr0grog** [comment]
If we do that, we probably need to do a serious permissions audit first. I’m a little unsure this org is ever going to be a particularly secure place for sensitive info, though :\

Then again, maybe this is just another instance of: put most stuff in public on GitHub, put all secrets in Keybase.

**Comment by danielballan** [comment]
> Then again, maybe this is just another instance of: put most stuff in public on GitHub, put all secrets in Keybase.

From my perspective, that approach has served us well. And I like the idea of keeping our _procedures_ public on principle.

**Comment by Mr0grog** [comment]
Since this sue was created, we’ve also made a private git repo on Keybase for secrets. We should probably continue to be we that as a more organized place for any especially sensitive docs.

**Comment by Mr0grog** [comment]
I need to follow up on this, especially since my availability for this projects will be lessening soon.

**Comment by Mr0grog** [comment]
This was done in #36.
