### ISSUE TITLE
Broken aws workshop link in README

### ISSUE THREAD

**Issue by thedtripp** [edgi-govdata-archiving/web-monitoring-ops#25]
This link at the very bottom of the README is broken and doesn't go anywhere.

https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/developer-concepts

**Comment by Mr0grog** [comment]
@danielballan is this the equivalent page to what you were linking before? https://github.com/aws-samples/aws-workshop-for-kubernetes/tree/master/01-path-basics/103-kubernetes-concepts

**Comment by Mr0grog** [comment]
Fixing this to the best of my ability in #32. (Also adding permalinks for when this eventually happens again.)
