### ISSUE TITLE
Rename this repo?

### ISSUE THREAD

**Issue by Mr0grog** [edgi-govdata-archiving/web-monitoring-ops#4]
We’ve talked several times about how this repo should host all our deployment info, including scripts and tools for managing non-Kubernetes resources (e.g. the scraper instance, our RDS and Elasticache instances, etc).

To that end, I feel like we should rename this repo. Maybe `web-monitoring-deploy`?

**Comment by danielballan** [comment]
Fine by me.

**Comment by Mr0grog** [comment]
> maybe `web-monitoring-ops`?

👍

**Comment by Mr0grog** [comment]
Done.
